name: Draft Github Release

on:
  pull_request:
    branches:
      - staging
    types: [closed]

jobs:
  update_release_draft:
    uses: deepworks-net/github.actions/.github/workflows/release-drafter.yml@main
    with:
      config-path: .github/release-drafter.yml