name: Update Changelog

on:
  pull_request:
    branches:
      - staging
    types: [closed]

jobs:
  update_changelog:
    uses: deepworks-net/github.actions/.github/workflows/update-changelog.yml@v1.0.103